In [2]:
# Evaluate
# get_rank_52_holdem
# get_hand_rank_all_hands_on_given_boards_52_holdem
# by giving them worst and best hands/boards

In [3]:

from typing import List

import numpy as np
from prl.environment.Wrappers.prl_wrappers import AugmentObservationWrapper
from prl.environment.steinberger.PokerRL.game._.cpp_wrappers.CppHandeval import CppHandeval
# from prl.environment.steinberger.PokerRL.game._.cpp_wrappers.CppLUT import CppLibHoldemLuts

from prl.baselines.supervised_learning.data_acquisition.environment_utils import build_cards_state_dict, init_wrapped_env, make_player_cards, make_board_cards

cpp_poker = CppHandeval()
# luts = CppLibHoldemLuts()


def setup(board: str, player_hands: List[str]):
    cards_state_dict = build_cards_state_dict(board, player_hands)
    env: AugmentObservationWrapper = init_wrapped_env(env_wrapper_cls=AugmentObservationWrapper,
                                                      stack_sizes=[100, 110, 120, 130, 140, 150])
    state_dict = {'deck_state_dict': cards_state_dict}
    return env, state_dict


def notes():
    # b = np.array([[2, 0], [2, 3], [11, 1], [10, 2], [11, 2]], dtype=np.int8)
    # h = np.array([[11, 3], [5, 1]], dtype=np.int8)
    # Act
    # obs, _, done, _ = wrapped_env.reset(config=state_dict)
    # todo: --- ASSERT ---
    # parse initial observation back to cards
    # step 5 time and check the other players cards
    # Assert
    assert True



In [4]:
# board = '['' '' '' '' '']'
board = '[6h Ts Td 9c Jc]'  # we need specify board to bootstrap env from state dict
# player_hands = ['3h 3c', 'Tc 9s', 'Jd Js', 'Kc Ks', 'Ac Ad', '2h 2c']
player_hands = ['7d 2h', '2h 7d', 'Ac As', 'Kc Ks', '2h 2c']
wrapped_env, state_dict = setup(board, player_hands)
lh = wrapped_env.env.get_lut_holder()
feature_names = list(wrapped_env.obs_idx_dict.keys()) + ["button_index"]

In [5]:
player_cards = make_player_cards(player_hands)
board_cards = make_board_cards(board)
player_cards[1]

[[0, 0], [5, 1]]

In [6]:
type(player_cards[0])

list

In [1]:
import numpy as np
from numba import njit
arr = np.array([0 for _ in range(80)])

In [11]:
%%timeit

@njit
def f():
    deck = []
    for i in range(51):
        deck.append(i)
    deck = np.array(deck)
    return np.random.choice(deck, 6, replace=False)
print(f())

[50 40 37 25 49 23]
[10 42  5 14 46  8]
[25 17 40 23 14 18]
[39 11 13 27 33 14]
[ 0 25 10 12 26 39]
[48  5 25 27 46  6]
[ 9 17 49 30 12 13]
[ 0 23 44  7 24  3]
249 ms ± 48.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
