In [2]:
# Evaluate
# get_rank_52_holdem
# get_hand_rank_all_hands_on_given_boards_52_holdem
# by giving them worst and best hands/boards

In [3]:

from typing import List

import numpy as np
from prl.environment.Wrappers.augment import AugmentObservationWrapper
from prl.environment.steinberger.PokerRL.game._.cpp_wrappers.CppHandeval import CppHandeval
# from prl.environment.steinberger.PokerRL.game._.cpp_wrappers.CppLUT import CppLibHoldemLuts

from prl.baselines.supervised_learning.data_acquisition.environment_utils import build_cards_state_dict, init_wrapped_env, make_player_cards, make_board_cards

cpp_poker = CppHandeval()
# luts = CppLibHoldemLuts()


def setup(board: str, player_hands: List[str]):
    cards_state_dict = build_cards_state_dict(board, player_hands)
    env: AugmentObservationWrapper = init_wrapped_env(env_wrapper_cls=AugmentObservationWrapper,
                                                      stack_sizes=[100, 110, 120, 130, 140, 150])
    state_dict = {'deck_state_dict': cards_state_dict}
    return env, state_dict


def notes():
    # b = np.array([[2, 0], [2, 3], [11, 1], [10, 2], [11, 2]], dtype=np.int8)
    # h = np.array([[11, 3], [5, 1]], dtype=np.int8)
    # Act
    # obs, _, done, _ = wrapped_env.reset(config=state_dict)
    # todo: --- ASSERT ---
    # parse initial observation back to cards
    # step 5 time and check the other players cards
    # Assert
    assert True



In [4]:
# board = '['' '' '' '' '']'
board = '[6h Ts Td 9c Jc]'  # we need specify board to bootstrap env from state dict
# player_hands = ['3h 3c', 'Tc 9s', 'Jd Js', 'Kc Ks', 'Ac Ad', '2h 2c']
player_hands = ['7d 2h', '2h 7d', 'Ac As', 'Kc Ks', '2h 2c']
wrapped_env, state_dict = setup(board, player_hands)
lh = wrapped_env.env.get_lut_holder()
feature_names = list(wrapped_env.obs_idx_dict.keys()) + ["button_index"]

In [5]:
player_cards = make_player_cards(player_hands)
board_cards = make_board_cards(board)
player_cards[1]

[[0, 0], [5, 1]]

In [6]:
type(player_cards[0])

list

In [12]:
import numpy as np
from numba import njit
arr = np.array([0 for _ in range(80)])

deck = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51])

In [16]:
%%timeit
@njit
def f():
    return np.random.choice(deck, 6, replace=False)
print(f())

[22  8 42  5 31 14]
[39 13  9 41 31 40]
[39 31 17 45 35 11]
[40 45 24  8 26  7]
[35 37  9 42 38 45]
[29  2  7 13 31 41]
[ 2 12 34 16 43 50]
[42  2  8 35 18  9]
275 ms ± 42.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%%timeit
print(f())

NameError: name 'f' is not defined